### ISSUE TITLE
[BUG] napari widget align transform need some kind of centering?

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe-template-builder#24]
**Describe the bug**
Using the `napari` widget to align `najva4` sample gives this screenshot after (what I think is a sensible choice of mid-plane points)
![image](https://github.com/user-attachments/assets/8dfaed66-22cf-4d99-a817-1a9e0bdf88ae)

The alignment seems to work well in the sense that the AP axis is as expected.
But the centre is off?

**To Reproduce**
Walk through the `napari` pre-processing widget with the `najva4` sample.

**Expected behaviour**
Sensible choice of mid-plane results in sensible-ish hemisphere.

**Computer used (please complete the following information):**
Ubuntu 22 on Dell Desktop

**Comment by niksirbi** [comment]
Alright, the first manifestation of the bug (estimated points being out of the mask), is no big mystery. My code just ensures that these points will be aligned with the mask's centroid along the symmetry axis (left-right axis). There is no guarantee that the 9 points will fall within the mask itself. That's because the code is written implicitly assuming that the brain will fill most of the field of view, which it clearly doesn't.

See the offending functions is [here](https://github.com/brainglobe/brainglobe-template-builder/blob/9de1c5a9e158a967e9601477bb1a7068bf1425de/brainglobe_template_builder/preproc/alignment.py#L64).

I think we should change to actually using the mask's bounding box during point estimation, instead of the whole image.

**Comment by niksirbi** [comment]
Actually, the 9 points are within the mask in 2/3 axes. It's only along the y axis (axis=1) that they are out of bounds. I'll look into it.
